name: ci-pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

###
# Optional: prevent multiple CI runs for the same ref
###
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # --- Validate Terraform in tf_enviournments ---
  terraform_validate_configuration:
    name: Terraform validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tf_enviournments
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
          terraform_wrapper: false

      - name: Terraform Format Check
        run: terraform fmt #-check -recursive -diff

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

  # Preparing a Docker requirements for artifact
  prepare_docker_environment:
    name: Preparing a Docker requirements for artifact
    needs: [ terraform_validate_configuration ]
    runs-on: ubuntu-latest
    outputs:
      meta_tags_output: ${{ steps.docker_metadata.outputs.tags }} 
      meta_labels_output: ${{ steps.docker_metadata.outputs.labels}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
     
      - name: Extract metadata (tags, labels) for Docker
        id: docker_metadata
        uses: docker/metadata-action@v6
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/cicd_pipeline_dockerhub
          tags: |
            type=schedule, pattern={{date 'YYYYMMDD'}}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Print Docker metadata
        run: |
          echo "Docker metadata1: ${{ toJson(steps.docker_metadata.outputs) }}"
          echo "Docker metadata2: ${{ toJson(steps.docker_metadata) }}"
      
      # - name: Upload Docker Meta Data Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: docker_meta_artifact
      #     path: ${{ runner.temp }}/bake-meta.json
      #     if-no-files-found: error
      #     retention-days: 1

  # Build Artifact Repository: Push docker image to Docker Hub or Amazon ECR store, produce artifact for CD --- containerization
  build_artifact_docker_image:
    needs: [ prepare_docker_environment, terraform_validate_configuration ]
    name: Build Artifact Image and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub 
        uses: docker/login-action@v4
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          platforms: linux/amd64, linux/arm64
          # Note: metadata-action handles the image name + tags together
          # tags: ${{ steps.meta.outputs.tags}}
          # labels: ${{ steps.meta.outputs.labels }}  
          tags: ${{ needs.prepare_docker_environment.outputs.meta_tags_output.outputs.tags}}
          labels: ${{ needs.prepare_docker_environment.outputs.meta_labels_output.outputs.labels }}  
          # tags: prabhushan/test-service:${{ github.ref_name }}-${{ github.sha }}

      - name: Inspect
        run: |
          docker image inspect ${{ secrets.DOCKER_USERNAME }}/cicd_pipeline_dockerhub:*


  # --- Unit / integration tests ---
  unit_tests:
    name: Unit tests
    needs: [ terraform_validate_configuration, build_artifact_docker_image ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          echo "Running unit tests..."
          # Add your test commands here, e.g.:
          # npm test
          # pytest
          # go test ./...

  # --- Security scan: Docker image vulnerability scanning  --- Docker Container Security Scanningner for vulnerabilities- 
  scan_docker_container:
    name: Security scanning Docker Image for vulnerabilities
    needs: [ terraform_validate_configuration, build_artifact_docker_image, unit_tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run security checks
        run: |
          echo "Running security scan..."
          # Optional: add Trivy, CodeQL, or other scanners
          
      # - name: Scan Docker Image for vulnerabilities
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: myapp:scan
      #     format: 'sarif'
      #     output: 'trivy-results.sarif'
      #     severity: 'CRITICAL,HIGH'

  # --- Workflow only succeeds when all jobs pass  ---
  ci-success:
    name: CI success
    runs-on: ubuntu-latest
    needs: [terraform_validate_configuration, build_artifact_docker_image, unit_tests, scan_docker_container]
    steps:
      - run: echo "All CI jobs completed successfully."
